vich_uploader:
    db_driver: orm

    mappings:
        users:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'

        categories:
            uri_prefix: /images/categories
            upload_destination: '%kernel.project_dir%/public/images/categories'

        products:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'

        services:
            uri_prefix: /images/services
            upload_destination: '%kernel.project_dir%/public/images/services'

